# Generated by Django 3.1.6 on 2021-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=300)),
                ('BookAuthor', models.CharField(max_length=200)),
                ('BookDesc', models.TextField()),
                ('BookPrice', models.IntegerField()),
                ('BookQty', models.IntegerField()),
            ],
        ),
    ]
