# Generated by Django 3.1.6 on 2021-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16)),
                ('UserPassword', models.CharField(max_length=30)),
                ('UserFirstname', models.CharField(max_length=100)),
                ('Userlastname', models.CharField(max_length=100)),
                ('UserBday', models.CharField(max_length=100)),
            ],
        ),
    ]
