# Generated by Django 3.1.6 on 2021-02-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=100),
        ),
    ]
