# Generated by Django 3.1.6 on 2021-02-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210216_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
