# Generated by Django 3.1.6 on 2021-02-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210217_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='UserID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
