# Generated by Django 3.1.6 on 2021-02-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_cart_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=300)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentPrice', models.IntegerField()),
                ('PaymentStatus', models.BooleanField()),
                ('AddressID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('CartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
