# Generated by Django 3.1.6 on 2021-02-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_address_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='PaymentStatus',
        ),
    ]
