# Generated by Django 3.1.6 on 2021-02-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='PaymentPrice',
        ),
    ]
