# Generated by Django 3.1.6 on 2021-02-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210218_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='CartPrice',
            field=models.FloatField(),
        ),
    ]
