# Generated by Django 3.1.6 on 2021-02-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210218_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Payment',
        ),
    ]
