# Generated by Django 3.1.6 on 2021-02-18 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_remove_cart_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='BookID',
        ),
        migrations.AddField(
            model_name='cart',
            name='BookID',
            field=models.ManyToManyField(to='app.Book'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='UserID',
        ),
        migrations.AddField(
            model_name='cart',
            name='UserID',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
