# Generated by Django 3.1.6 on 2021-02-18 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_auto_20210218_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='BookID',
        ),
        migrations.AddField(
            model_name='cart',
            name='BookID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.book'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='UserID',
        ),
        migrations.AddField(
            model_name='cart',
            name='UserID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
