# Generated by Django 3.1.6 on 2021-02-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210218_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='BookQty',
            new_name='Total',
        ),
    ]
