# Generated by Django 3.1.6 on 2021-02-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210218_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='BookID',
        ),
    ]
