# Generated by Django 3.1.6 on 2021-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='books',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
