# Generated by Django 3.1.6 on 2021-02-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_payment_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='books',
            field=models.TextField(),
        ),
    ]
