# Generated by Django 3.1.6 on 2021-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210218_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='books',
        ),
        migrations.AddField(
            model_name='payment',
            name='books',
            field=models.ManyToManyField(to='app.Book'),
        ),
    ]
