# Generated by Django 3.1.6 on 2021-02-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210218_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book'),
        ),
    ]
