# Generated by Django 3.1.6 on 2021-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210218_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='books',
        ),
        migrations.AddField(
            model_name='payment',
            name='books',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
