# Generated by Django 3.1.6 on 2021-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210218_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='BookID',
        ),
        migrations.AddField(
            model_name='payment',
            name='BookID',
            field=models.ManyToManyField(to='app.Book'),
        ),
    ]
