# Generated by Django 3.1.6 on 2021-02-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210218_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='BookID',
        ),
        migrations.AddField(
            model_name='payment',
            name='BookID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.book'),
            preserve_default=False,
        ),
    ]
