# Generated by Django 3.1.6 on 2021-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20210218_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
